Fix invalid conversion errors for Ogre ExceptionCodes [-fpermissive]
Fixes the following GCC 8 error:
error: invalid conversion from 'int' to 'Ogre::Exception::ExceptionCodes' [-fpermissive]

Used ERR_INVALIDPARAMS in some places where ERR_INVALID_CALL would be more
appropriate, because ERR_INVALID_CALL is new in Ogre 1.10+ and using it
would break Ogre 1.9 support.