Fix narrowing conversion issue [-Wnarrowing]
Fixes the following issue on aarch64 with GCC 8.1:
source/editor/TerrainBrushes.cpp:138:1: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]

The signedness of 'char' is implementation defined, so we need to be explicit.